server:
  port: 19088
spring:
  application:
    name: gateway
zuul:
  routes:
eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:9874/eureka/
logging:
  config: classpath:logback.xml
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
